# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - devtools

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
