#' Generate data
#' 
#' Generate nodes and edges.
#'
#' @param n Number of nodes.
#' @param colors Color palette to use.
#' @param nodes Nodes, as generated by \code{sg_make_nodes}.
#'
#' @examples
#' nodes <- sg_make_nodes()
#' edges <- sg_make_edges(nodes)
#' 
#' sigmajs() %>%
#'	sg_nodes(nodes, id, label, size, color) %>%
#'	sg_edges(edges, id, source, target) %>%
#'	sg_settings(defaultNodeColor = "#0011ff")
#' 
#' @return \code{tibble} of nodes or edges.
#'
#' @importFrom grDevices colorRampPalette
#' @rdname generate
#' @export
sg_make_nodes <- function(n = 10, colors = c("#B1E2A3", "#98D3A5", "#328983", "#1C5C70", "#24C96B")) {

	dplyr::tibble(
		id = as.character(seq(1, n)),
		label = sample(LETTERS, n, replace = TRUE),
		size = ceiling(runif(n, 1, 5)),
		color = colorRampPalette(colors)(n)
	)

}

#' @rdname generate
#' @export
sg_make_edges <- function(nodes, n = 15) {
	ids <- as.character(nodes$id)

	dplyr::tibble(
		id = seq(1, n),
		source = sample(ids, n, replace = TRUE),
		target = sample(ids, n, replace = TRUE)
	)
}